language: android
jdk:
  - oraclejdk8
android:
  components:
    - tools
    - build-tools-26.0.2
    - android-27
    - extra-google-m2repository
    - extra-android-m2repository
  licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
before_install:
   - export JAVA8_HOME=/usr/lib/jvm/java-8-oracle
   - touch local.properties
   - yes | sdkmanager "platforms;android-26.0.2"
script:
   - ./gradlew check
